name: XTC OTA

on:
  workflow_dispatch:

jobs:
  find-ota:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run OTA finder
      run: |
        start_time=1726070400
        end_time=1726156800
        i=$start_time
        found=false

        while [ $i -le $end_time ]; do
          url="http://t.xiaotiancai.com/ota_f_v1.0.0_t${i}.zip?s=449:FoanUhtP?任意字符=任意字符"
          echo "尝试下载: $url"
          curl -sS -o ota.zip "$url" 2>log

          file_size=$(stat -c%s "ota.zip" 2>/dev/null || echo 0)
          if [ "$file_size" -gt 943718400 ]; then
            echo "找到大文件! 下载链接: $url"
            echo "文件大小: $((file_size/1024/1024))MB"
            echo $i > found_i.txt
            found=true
            break
          fi
          cat ota.zip

          i=$((i + 1))
        done

        if [ "$found" = false ]; then
          echo "未找到符合条件的文件"
          exit 1
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ota-found-${{ github.run_id }}
        release_name: OTA Found ${{ github.run_id }}
        draft: false
        prerelease: false

    - name: Upload Result
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: found_i.txt
        asset_name: found_i.txt
        asset_content_type: text/plain